[package]
name = "perpetualtest"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
perpetual = "=0.8.0"
polars = { version = "0.46.0", features = ["pivot"] }
